# Generated by Django 3.2.4 on 2021-06-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='participation_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('current', models.TextField()),
                ('institute', models.CharField(max_length=100)),
                ('doubt', models.TextField()),
                ('subscribe', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
